name: glennscrap
email: gweatherson@gmail.com
title: glennscrap
description: A place filled with photos of bikes, dogs, friends, and other nonsense.
baseurl: ""
url: "https://glennscrap.com"
permalink: pretty
markdown: kramdown
highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]
